In [1]:
import tensorflow as tf

### Tensors and Operations


In [19]:
t = tf.constant([[1, 2, 3], [4, 5, 6]])
t

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [20]:
t.shape

TensorShape([2, 3])

In [21]:
t.numpy()

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
print(t[0, 0])
print(t[:, 2])

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([3 6], shape=(2,), dtype=int32)


In [23]:
t[..., :]

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [24]:
t[..., 1, tf.newaxis]  # keep dimension 1

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[2],
       [5]])>

In [25]:
t+10

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[11, 12, 13],
       [14, 15, 16]])>

In [26]:
t.__add__(10)  # not in-place

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[11, 12, 13],
       [14, 15, 16]])>

In [27]:
t

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [28]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  4,  9],
       [16, 25, 36]])>

In [29]:
t @ tf.transpose(t)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 32],
       [32, 77]])>

### Tensors and NumPy


In [30]:
import numpy as np

In [31]:
a = np.array([2., 4., 5.])
tf.constant(a)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2., 4., 5.])>

In [32]:
tf.square(a)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 4., 16., 25.])>

In [33]:
np.square(t)

array([[ 1,  4,  9],
       [16, 25, 36]])

### Type Conversions


In [34]:
try:
    tf.constant(2.0) + tf.constant(40)
except tf.errors.InvalidArgumentError as ex:
    print(ex)

cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a int32 tensor [Op:AddV2] name: 


In [35]:
try:
    tf.constant(2.0) + tf.constant(40., dtype=tf.float64)
except tf.errors.InvalidArgumentError as ex:
    # defualt values in tensorflow are float32, cannot manipulated with float64
    print(ex)

cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a double tensor [Op:AddV2] name: 


In [36]:
tf.constant(2.) + tf.constant(50, dtype=tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=52.0>

In [37]:
t2 = tf.constant(40, dtype=tf.float64)
tf.constant(2.) + tf.cast(t2, tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=42.0>

### Variables


In [38]:
v = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [39]:
v.assign(2*v)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

In [40]:
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

In [41]:
v[0, 0].assign(42)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[42.,  4.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

In [42]:
v.scatter_nd_update(indices=[[0, 0], [1, 0]], updates=[100, 400])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[100.,   4.,   6.],
       [400.,  10.,  12.]], dtype=float32)>

In [43]:
try:
    t[1] = [7., 8., 9.]  # cannot update with direct assignment
except TypeError as ex:
    print(ex)

'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment


### Custom Loss Function


In [44]:
def huber_fn(y_true, y_pred):
    """combine MSE smoothing property (at small values) and MAE outliers robustness property (at large values)"""
    error = abs(y_true-y_pred)
    squared = tf.square(error) / 2  # smoothing gradients factor
    # -.5 for connection guaranteed between two losses at the threshold (1 here)
    linear = error - .5
    return tf.where(error < 1, squared, linear)

In [45]:
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

housing = fetch_california_housing()
X_train_full, X_test, y_train_full, y_test = train_test_split(
    housing.data, housing.target.reshape(-1, 1), random_state=42)
X_train, X_valid, y_train, y_valid = train_test_split(
    X_train_full, y_train_full, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_valid_scaled = scaler.transform(X_valid)
X_test_scaled = scaler.transform(X_test)

input_shape = X_train.shape[1:]

tf.keras.utils.set_random_seed(42)
model = tf.keras.Sequential([
    tf.keras.layers.Dense(30, activation="relu", kernel_initializer="he_normal",
                          input_shape=input_shape),
    tf.keras.layers.Dense(1),
])

C:\Users\sayed\AppData\Roaming\Python\Python310\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [46]:
model.compile(loss=huber_fn, metrics=['mae'], optimizer='nadam')

model.fit(X_train_scaled, y_train, epochs=2,
          validation_data=(X_valid_scaled, y_valid))

Epoch 1/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.7494 - mae: 1.1371 - val_loss: 0.3474 - val_mae: 0.6522
Epoch 2/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - loss: 0.2607 - mae: 0.5681 - val_loss: 0.2553 - val_mae: 0.5383


### Saving/Loading Models with Custom objects


In [47]:
import os
os.makedirs('saved_models', exist_ok=True)

In [48]:
model.save('saved_models/my_model_with_custom_hyper_loss.keras')

Load the model:


In [49]:
model = tf.keras.models.load_model(
    'saved_models/my_model_with_custom_hyper_loss.keras', custom_objects={'huber_fn': huber_fn})

In [50]:
model.fit(X_train_scaled, y_train, epochs=2,
          validation_data=(X_valid_scaled, y_valid))

Epoch 1/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2188 - mae: 0.5096 - val_loss: 0.2129 - val_mae: 0.4876
Epoch 2/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 953us/step - loss: 0.1990 - mae: 0.4809 - val_loss: 0.1891 - val_mae: 0.4610


#### Now, We need to control the threshold..


In [51]:
def create_huber(threshold=1.0):
    def huber_fn(y_true, y_pred):
        error = y_true - y_pred
        is_small_error = tf.abs(error) < threshold
        squared_loss = tf.square(error) / 2
        linear_loss = threshold * tf.abs(error) - threshold ** 2 / 2
        return tf.where(is_small_error, squared_loss, linear_loss)
    return huber_fn

In [52]:
model.compile(loss=create_huber(2.0), metrics=['mae'], optimizer='nadam')

In [53]:
model.fit(X_train_scaled, y_train, epochs=2,
          validation_data=(X_valid_scaled, y_valid))

Epoch 1/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.2148 - mae: 0.4689 - val_loss: 0.2084 - val_mae: 0.4504
Epoch 2/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.2054 - mae: 0.4597 - val_loss: 0.1807 - val_mae: 0.4340


In [54]:
model.save("saved_models/my_model_with_a_custom_loss_threshold_2.keras")

In [55]:
model = tf.keras.models.load_model("saved_models/my_model_with_a_custom_loss_threshold_2.keras",
                                   custom_objects={"huber_fn": create_huber(2.0)})

so the threshold will not be saved with the model, but we must pass it..


In [56]:
model.fit(X_train_scaled, y_train, epochs=2,
          validation_data=(X_valid_scaled, y_valid))

Epoch 1/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.2000 - mae: 0.4540 - val_loss: 0.1853 - val_mae: 0.4339
Epoch 2/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 923us/step - loss: 0.1959 - mae: 0.4490 - val_loss: 0.1976 - val_mae: 0.4367


now we need to build huber function that saves the threshold with it, we must use sub-classing..


In [57]:
import keras

### Sub-Classing Custom Loss Function with automatically saved hyperparameters


In [58]:
@keras.utils.register_keras_serializable()
class HuberLoss(tf.keras.losses.Loss):
    def __init__(self, threshold=1.0, **kwargs):
        self.threshold = threshold
        super().__init__(**kwargs)

    def call(self, y_true, y_pred):
        error = y_true - y_pred
        is_small_error = tf.abs(error) < self.threshold
        squared_loss = tf.square(error) / 2
        linear_loss = self.threshold * tf.abs(error) - self.threshold**2 / 2
        return tf.where(is_small_error, squared_loss, linear_loss)

    def get_config(self):
        base_config = super().get_config()
        return {**base_config, "threshold": self.threshold}

In [59]:
tf.keras.utils.set_random_seed(42)
model = tf.keras.Sequential([
    tf.keras.layers.Dense(30, activation="relu", kernel_initializer="he_normal",
                          input_shape=input_shape),
    tf.keras.layers.Dense(1),
])

model.compile(loss=HuberLoss(2.), optimizer="nadam", metrics=["mae"])

model.fit(X_train_scaled, y_train, epochs=2,
          validation_data=(X_valid_scaled, y_valid))

Epoch 1/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 1.0512 - mae: 1.1438 - val_loss: 0.5086 - val_mae: 0.6718
Epoch 2/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 794us/step - loss: 0.3170 - mae: 0.5816 - val_loss: 0.3527 - val_mae: 0.5571


In [60]:
model.save("saved_models/my_model_with_a_custom_loss_class.keras")

> Note: when using sub-classing, either passing the custom class used as custom objects, or decorate the class with @keras.utils.register_keras_serializable(),


In [61]:
model = tf.keras.models.load_model('saved_models/my_model_with_a_custom_loss_class.keras'
                                   #    ,custom_objects={'HuberLoss': HuberLoss}
                                   )

In [62]:
model.loss

here's, it identify it even without passing it as custom object to load_model function


---


### Custom Activation Functions, Initializers, Regularizers,and Constraints


In [63]:
def my_softplus(z):
    return tf.math.log(1.0 + tf.exp(z))


def my_glorot_initializer(shape, dtype=tf.float32):
    stddev = tf.sqrt(2. / (shape[0] + shape[1]))
    return tf.random.normal(shape, stddev=stddev, dtype=dtype)


def my_l1_regularizer(weights):
    return tf.reduce_sum(tf.abs(0.01 * weights))


def my_positive_weights(weights):  # return value is just tf.nn.relu(weights)
    return tf.where(weights < 0., tf.zeros_like(weights), weights)

In [64]:
layer = tf.keras.layers.Dense(1, activation=my_softplus,
                              kernel_initializer=my_glorot_initializer,
                              kernel_regularizer=my_l1_regularizer,
                              kernel_constraint=my_positive_weights)

Full example using custom functions above


In [65]:
tf.keras.utils.set_random_seed(42)

try:
    model = tf.keras.Sequential([
        tf.keras.layers.Dense(30, activation="relu", kernel_initializer="he_normal",
                              input_shape=input_shape),
        tf.keras.layers.Dense(1, activation=my_softplus,
                              kernel_initializer=my_glorot_initializer,
                              kernel_regularizer=my_l1_regularizer,
                              kernel_constraint=my_positive_weights)
    ])
    model.compile(loss="mse", optimizer="nadam", metrics=["mae"])
    model.fit(X_train_scaled, y_train, epochs=2,
              validation_data=(X_valid_scaled, y_valid))
    model.save("saved_models/my_model_with_many_custom_parts")
    model = tf.keras.models.load_model(
        "saved_models/my_model_with_many_custom_parts",
        custom_objects={
            "my_l1_regularizer": my_l1_regularizer,
            "my_positive_weights": my_positive_weights,
            "my_glorot_initializer": my_glorot_initializer,
            "my_softplus": my_softplus,
        }
    )
    model.fit(X_train_scaled, y_train, epochs=2,
              validation_data=(X_valid_scaled, y_valid))

except Exception as ex:
    print(ex)

Invalid value for attribute `regularizer`. Expected an instance of `keras.regularizers.Regularizer`, or `None`. Received: regularizer=<function my_l1_regularizer at 0x0000015D4BC555A0>


here's a problem with directly assignment regular functions, we should do it with sub-classing


In [66]:
# Custom Regularizer
class MyL1Regularizer(tf.keras.regularizers.Regularizer):
    def __init__(self, factor=0.01):
        self.factor = factor

    def __call__(self, x):
        return tf.reduce_sum(tf.abs(self.factor * x))

    def get_config(self):
        return {"factor": self.factor}

# Custom Constraint


class MyPositiveWeights(tf.keras.constraints.Constraint):
    def __call__(self, weights):
        return tf.nn.relu(weights)

    def get_config(self):
        return {}

# Custom Initializer


class MyGlorotInitializer(tf.keras.initializers.Initializer):
    def __init__(self):
        super(MyGlorotInitializer, self).__init__()

    def __call__(self, shape, dtype=tf.float32):
        stddev = tf.sqrt(2. / (shape[0] + shape[1]))
        return tf.random.normal(shape, stddev=stddev, dtype=dtype)

    def get_config(self):
        return {}

# Custom Activation Function


def my_softplus(z):
    return tf.math.log(1.0 + tf.exp(z))

In [67]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(30, activation="relu", kernel_initializer="he_normal",
                          input_shape=input_shape),
    tf.keras.layers.Dense(1, activation=my_softplus,
                          kernel_initializer=MyGlorotInitializer(),
                          kernel_regularizer=MyL1Regularizer(),
                          kernel_constraint=MyPositiveWeights())
])

model.compile(loss="mse", optimizer="nadam", metrics=["mae"])

# Fit model
model.fit(X_train_scaled, y_train, epochs=2,
          validation_data=(X_valid_scaled, y_valid))

# Save model
model.save("saved_models/my_model_with_many_custom_parts.keras")

# Load model
model = tf.keras.models.load_model(
    "saved_models/my_model_with_many_custom_parts.keras",
    custom_objects={
        "MyL1Regularizer": MyL1Regularizer,
        "MyPositiveWeights": MyPositiveWeights,
        "MyGlorotInitializer": MyGlorotInitializer,
        "my_softplus": my_softplus,
    }
)

# Continue training
model.fit(X_train_scaled, y_train, epochs=2,
          validation_data=(X_valid_scaled, y_valid))

Epoch 1/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 2.2008 - mae: 0.9706 - val_loss: inf - val_mae: inf
Epoch 2/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1.1249 - mae: 0.6767 - val_loss: inf - val_mae: inf
Epoch 1/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.8456 - mae: 0.5999 - val_loss: 2.8737 - val_mae: 0.5737
Epoch 2/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.6909 - mae: 0.5547 - val_loss: 2.0950 - val_mae: 0.5363


### Custom Metrics


In [68]:
# extra code – once again, lets' create a basic Keras model
tf.keras.utils.set_random_seed(42)
model = tf.keras.Sequential([
    tf.keras.layers.Dense(30, activation="relu", kernel_initializer="he_normal",
                          input_shape=input_shape),
    tf.keras.layers.Dense(1),
])
model.compile(loss="mse", optimizer="nadam", metrics=[create_huber(2.0)])

model.fit(X_train_scaled, y_train, epochs=2)

Epoch 1/2


363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 704us/step - huber_fn: 1.0788 - loss: 2.5942
Epoch 2/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 618us/step - huber_fn: 0.3403 - loss: 0.7644


#### Streaming metrics


In [69]:
precision = tf.keras.metrics.Precision()
precision([0, 1, 1, 1, 0, 1, 0, 1], [1, 1, 0, 1, 0, 1, 0, 1])

<tf.Tensor: shape=(), dtype=float32, numpy=0.8>

In [70]:
precision([0, 1, 0, 0, 1, 0, 1, 1], [1, 0, 1, 1, 0, 0, 0, 0])

<tf.Tensor: shape=(), dtype=float32, numpy=0.5>

In [71]:
precision.result()

<tf.Tensor: shape=(), dtype=float32, numpy=0.5>

In [72]:
precision.variables

[<KerasVariable shape=(1,), dtype=float32, path=precision/true_positives>,
 <KerasVariable shape=(1,), dtype=float32, path=precision/false_positives>]

clear stored accumulated variables


In [73]:
precision.reset_state()
precision.result()

<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

Creating a streaming metric:


In [74]:
tf.keras.backend.clear_session()

In [75]:

@keras.utils.register_keras_serializable()
class HuberMetric(tf.keras.metrics.Metric):
    def __init__(self, threshold=1.0, **kwargs):
        super().__init__(**kwargs)  # handles base args (e.g., dtype)
        self.threshold = threshold
        self.huber_fn = create_huber(threshold)
        self.total = self.add_weight(
            name='total', initializer='zeros', shape=(), dtype=tf.float32)
        self.count = self.add_weight(
            name='count', initializer='zeros', shape=(), dtype=tf.float32)

    def update_state(self, y_true, y_pred, sample_weight=None):
        sample_metrics = self.huber_fn(y_true, y_pred)
        self.total.assign_add(tf.reduce_sum(sample_metrics))
        self.count.assign_add(tf.cast(tf.size(y_true), tf.float32))

    def result(self):
        return self.total / self.count

    def get_config(self):
        base_config = super().get_config()
        return {**base_config, "threshold": self.threshold}

In [76]:
m = HuberMetric(2.)

# total = 2 * |10 - 2| - 2²/2 = 14
# count = 1
# result = 14 / 1 = 14
m(tf.constant([[2.]]), tf.constant([[10.]]))

<tf.Tensor: shape=(), dtype=float32, numpy=14.0>

In [77]:
# total = total + (|1 - 0|² / 2) + (2 * |9.25 - 5| - 2² / 2) = 14 + 7 = 21
# count = count + 2 = 3
# result = total / count = 21 / 3 = 7
m(tf.constant([[0.], [5.]]), tf.constant([[1.], [9.25]]))

<tf.Tensor: shape=(), dtype=float32, numpy=7.0>

In [78]:
m.result()

<tf.Tensor: shape=(), dtype=float32, numpy=7.0>

In [79]:
print("Total:", m.total.numpy())  # This should print 21.0
print("Count:", m.count.numpy())  # This should print 3.0"

Total: 21.0
Count: 3.0


In [80]:
m.variables

[<KerasVariable shape=(), dtype=float32, path=huber_metric/total>,
 <KerasVariable shape=(), dtype=float32, path=huber_metric/count>]

In [81]:
m.reset_state()
m.variables

[<KerasVariable shape=(), dtype=float32, path=huber_metric/total>,
 <KerasVariable shape=(), dtype=float32, path=huber_metric/count>]

In [82]:
tf.keras.utils.set_random_seed(42)
model = tf.keras.Sequential([
    tf.keras.layers.Dense(30, activation="relu", kernel_initializer="he_normal",
                          input_shape=input_shape),
    tf.keras.layers.Dense(1),
])

model.compile(loss=create_huber(2.0), optimizer="nadam",
              metrics=[HuberMetric(2.0)])

In [83]:
model.fit(X_train_scaled, y_train, epochs=2)

Epoch 1/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 694us/step - huber_metric_1: 1.0512 - loss: 1.0512
Epoch 2/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 971us/step - huber_metric_1: 0.3170 - loss: 0.3170


In [84]:
model.save("saved_models/my_model_with_a_custom_metric.keras")

In [85]:
model = tf.keras.models.load_model(
    "saved_models/my_model_with_a_custom_metric.keras",
    custom_objects={
        "huber_fn": create_huber(2.0),
        "HuberMetric": HuberMetric
    }
)

In [86]:
model.fit(X_train_scaled, y_train, epochs=2)

Epoch 1/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 623us/step - huber_metric_1: 0.2612 - loss: 0.2612
Epoch 2/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 613us/step - huber_metric_1: 0.2328 - loss: 0.2328


In [87]:
try:
    model.metrics[-1].threshold
except Exception as ex:
    print(ex)

'CompileMetrics' object has no attribute 'threshold'


In [88]:
for metric in model.metrics:
    if isinstance(metric, HuberMetric):
        print(f"Huber Metric threshold: {metric.threshold}")

it seems like keras has updated from HOML tutorial, i will investigate where to find our threshold..


In [89]:
type(model.metrics[1])

keras.src.trainers.compile_utils.CompileMetrics

In [90]:
dir(model.metrics[-1])

['__annotations__',
 '__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_api_export_path',
 '_api_export_symbol_id',
 '_build_metrics_set',
 '_check_super_called',
 '_dtype',
 '_flat_metrics',
 '_flat_weighted_metrics',
 '_flatten_y',
 '_metrics',
 '_obj_type',
 '_tracker',
 '_unpickle_model',
 '_user_metrics',
 '_user_weighted_metrics',
 '_variables',
 'add_variable',
 'add_weight',
 'build',
 'built',
 'dtype',
 'from_config',
 'get_config',
 'metrics',
 'name',
 'output_names',
 'reset_state',
 'result',
 'stateless_reset_state',
 'stateless_result',
 'stateless_update_state',
 'update_state',
 'variables']

In [91]:
type(model.metrics[-1].metrics[0])

__main__.HuberMetric

In [92]:
model.metrics[-1].metrics[0].threshold

2.0

here it is :))))


Looks like it works fine! More simply, we could have created the class like this:


In [93]:
class HuberMetric(tf.keras.metrics.Mean):
    def __init__(self, threshold=1.0, name='HuberMetric', dtype=None):
        self.threshold = threshold
        self.huber_fn = create_huber(threshold)
        super().__init__(name=name, dtype=dtype)

    def update_state(self, y_true, y_pred, sample_weight=None):
        metric = self.huber_fn(y_true, y_pred)
        super(HuberMetric, self).update_state(metric, sample_weight)

    def get_config(self):
        base_config = super().get_config()
        return {**base_config, "threshold": self.threshold}

In [94]:
tf.keras.utils.set_random_seed(42)
model = tf.keras.Sequential([
    tf.keras.layers.Dense(30, activation="relu", kernel_initializer="he_normal",
                          input_shape=input_shape),
    tf.keras.layers.Dense(1),
])

model.compile(loss=tf.keras.losses.Huber(2.0), optimizer="nadam",
              weighted_metrics=[HuberMetric(2.0)])

np.random.seed(42)
sample_weight = np.random.rand(len(y_train))
history = model.fit(X_train_scaled, y_train, epochs=2,
                    sample_weight=sample_weight)

Epoch 1/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 597us/step - HuberMetric: 1.0599 - loss: 0.5274
Epoch 2/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 586us/step - HuberMetric: 0.3215 - loss: 0.1598


In [95]:
(history.history["loss"][0],
 history.history["HuberMetric"][0] * sample_weight.mean())

(0.3256884217262268, 0.32568849524955656)

In [96]:
model.save("saved_models/my_model_with_a_custom_metric_v2.keras")

In [97]:
model = tf.keras.models.load_model("saved_models/my_model_with_a_custom_metric_v2.keras",
                                   custom_objects={"HuberMetric": HuberMetric})

In [98]:
model.fit(X_train_scaled, y_train, epochs=2)

Epoch 1/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 597us/step - HuberMetric: 0.2627 - loss: 0.2262
Epoch 2/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 594us/step - HuberMetric: 0.2298 - loss: 0.1999


In [99]:
model.metrics[-1].metrics[-1].threshold

2.0

### Custom Layers


In [100]:
explayer = tf.keras.layers.Lambda(lambda x: tf.exp(x))

In [101]:
explayer(tf.constant([-1., 0., 1.]))

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.36787945, 1.        , 2.7182817 ], dtype=float32)>

or with sub-classing api


In [102]:
class MyDense(tf.keras.layers.Layer):
    def __init__(self, units, activation=None, **kwargs):
        super().__init__(**kwargs)
        self.units = units
        self.activation = tf.keras.activations.get(activation)

    def build(self, batch_input_shape):
        self.kernel = self.add_weight(
            name="kernel", shape=[batch_input_shape[-1], self.units],
            initializer="he_normal")
        self.bias = self.add_weight(
            name="bias", shape=[self.units], initializer="zeros")

    def call(self, X):
        return self.activation(X @ self.kernel + self.bias)

    def get_config(self):
        base_config = super().get_config()
        return {**base_config, "units": self.units,
                "activation": tf.keras.activations.serialize(self.activation)}

In [103]:
tf.keras.utils.set_random_seed(42)
model = tf.keras.Sequential([
    MyDense(30, activation="relu", input_shape=input_shape),
    MyDense(1)
])
model.compile(loss="mse", optimizer="nadam")
model.fit(X_train_scaled, y_train, epochs=2,
          validation_data=(X_valid_scaled, y_valid))
model.evaluate(X_test_scaled, y_test)
model.save("saved_models/my_model_with_a_custom_layer.keras")

Epoch 1/2


C:\Users\sayed\AppData\Local\Temp\ipykernel_9352\3097604586.py:3: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 926us/step - loss: 5.7265 - val_loss: 6.9255
Epoch 2/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 794us/step - loss: 0.9550 - val_loss: 2.6011
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 495us/step - loss: 0.7227


In [104]:
model = tf.keras.models.load_model("saved_models/my_model_with_a_custom_layer.keras",
                                   custom_objects={"MyDense": MyDense})
model.fit(X_train_scaled, y_train, epochs=2,
          validation_data=(X_valid_scaled, y_valid))

Epoch 1/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 913us/step - loss: 0.7034 - val_loss: 0.8613
Epoch 2/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 730us/step - loss: 0.5803 - val_loss: 0.4588


In [105]:
class MyMultiLayer(tf.keras.layers.Layer):
    def call(self, X):
        X1, X2 = X
        return X1+X2, X1*X2, X1/X2

In [106]:
inputs1 = tf.keras.layers.Input(shape=[2])
inputs2 = tf.keras.layers.Input(shape=[2])
MyMultiLayer()((inputs1, inputs2))

(<KerasTensor shape=(None, 2), dtype=float32, sparse=False, name=keras_tensor_20>,
 <KerasTensor shape=(None, 2), dtype=float32, sparse=False, name=keras_tensor_21>,
 <KerasTensor shape=(None, 2), dtype=float32, sparse=False, name=keras_tensor_22>)

In [107]:
X1, X2 = np.array([[3., 6.], [2., 7.]]), np.array([[6., 12.], [4., 3.]])
MyMultiLayer()((X1, X2))

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[ 9., 18.],
        [ 6., 10.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[18., 72.],
        [ 8., 21.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[0.5      , 0.5      ],
        [0.5      , 2.3333333]], dtype=float32)>)

Now let's create a layer with a different behavior during training and testing:


In [108]:
class MyGaussianNoise(tf.keras.layers.Layer):
    def __init__(self, stddev, **kwargs):
        super().__init__(**kwargs)
        self.stddev = stddev

    def call(self, X, training=None):
        if training:
            noise = tf.random.normal(tf.shape(X), stddev=self.stddev)
            return X + noise
        return X

In [109]:
tf.keras.utils.set_random_seed(42)
model = tf.keras.Sequential([
    MyGaussianNoise(stddev=1.0, input_shape=input_shape),
    tf.keras.layers.Dense(30, activation="relu",
                          kernel_initializer="he_normal"),
    tf.keras.layers.Dense(1)
])
model.compile(loss="mse", optimizer="nadam")
model.fit(X_train_scaled, y_train, epochs=2,
          validation_data=(X_valid_scaled, y_valid))
model.evaluate(X_test_scaled, y_test)

Epoch 1/2


C:\Users\sayed\AppData\Local\Temp\ipykernel_9352\1546716026.py:3: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 959us/step - loss: 2.7619 - val_loss: 25.1369
Epoch 2/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 793us/step - loss: 1.3951 - val_loss: 14.9793
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 497us/step - loss: 1.1219


1.1244221925735474

### Custom Models


In [110]:
tf.keras.backend.clear_session()

In [111]:
@tf.keras.utils.register_keras_serializable()
class ResidualBlock(tf.keras.layers.Layer):
    def __init__(self, n_layers, n_units, **kwargs):
        super().__init__(**kwargs)
        self.n_layers = n_layers
        self.n_units = n_units
        self.hidden = [tf.keras.layers.Dense(
            n_units, activation='relu', kernel_initializer="he_normal")
            for _ in range(n_layers)]

    def call(self, inputs):
        Z = inputs
        for layer in self.hidden:
            Z = layer(Z)
        return Z + inputs

    def get_config(self):
        config = super().get_config()
        config.update({
            "n_layers": self.n_layers,
            "n_units": self.n_units,
        })
        return config

In [112]:

@tf.keras.utils.register_keras_serializable()
class ResidualRegressor(tf.keras.models.Model):
    def __init__(self, output_dim, **kwargs):
        super().__init__(**kwargs)
        self.output_dim = output_dim
        self.linear1 = tf.keras.layers.Dense(30)
        self.rBlock1 = ResidualBlock(2, 30)
        self.rBlock2 = ResidualBlock(2, 30)
        self.out = tf.keras.layers.Dense(output_dim)

    def call(self, inputs):
        Z = self.linear1(inputs)
        for _ in range(1+3):
            Z = self.rBlock1(Z)
        Z = self.rBlock2(Z)
        return self.out(Z)

    def get_config(self):
        config = super().get_config()
        config.update({
            "output_dim": self.output_dim,
        })
        return config

In [113]:
tf.keras.utils.set_random_seed(42)
model = ResidualRegressor(1)
model.compile(loss="mse", optimizer="nadam")
history = model.fit(X_train_scaled, y_train, epochs=2)
score = model.evaluate(X_test_scaled, y_test)
model.save("saved_models/my_custom_model.keras")

model = tf.keras.models.load_model("saved_models/my_custom_model.keras")
history = model.fit(X_train_scaled, y_train, epochs=2)
model.predict(X_test_scaled[:3])

Epoch 1/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 2s 869us/step - loss: 38.7647
Epoch 2/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 811us/step - loss: 0.9498
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 560us/step - loss: 0.5812
Epoch 1/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 791us/step - loss: 0.6747
Epoch 2/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - loss: 0.5269
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step


array([[1.0190629],
       [1.8359567],
       [4.045906 ]], dtype=float32)

Losses and Metrics Based on Model Internals


In [114]:
tf.keras.backend.clear_session()

In [115]:
class ReconstructingRegressor(tf.keras.Model):
    def __init__(self, output_dim, **kwargs):
        super().__init__(**kwargs)
        self.hidden = [tf.keras.layers.Dense(30, activation="relu",
                                             kernel_initializer="he_normal")
                       for _ in range(5)]
        self.out = tf.keras.layers.Dense(output_dim)
        self.reconstruction_mean = tf.keras.metrics.Mean(
            name="reconstruction_error")

    def build(self, batch_input_shape):
        n_inputs = batch_input_shape[-1]
        self.reconstruct = tf.keras.layers.Dense(n_inputs)

    def call(self, inputs, training=None):
        Z = inputs
        for layer in self.hidden:
            Z = layer(Z)
        reconstruction = self.reconstruct(Z)
        recon_loss = tf.reduce_mean(tf.square(reconstruction - inputs))
        self.add_loss(0.05 * recon_loss)
        if training:
            result = self.reconstruction_mean(recon_loss)
            self.add_metric(result)
        return self.out(Z)

In [116]:
tf.keras.utils.set_random_seed(42)
try:
    model = ReconstructingRegressor(1)
    model.compile(loss="mse", optimizer="nadam")
    history = model.fit(X_train_scaled, y_train, epochs=5)
    y_pred = model.predict(X_test_scaled)
except:
    print('error due to changes in tf new version (add metric deleted)')

Epoch 1/5
error due to changes in tf new version (add metric deleted)


---


### Computing Gradients Using Autodiff


In [117]:
def f(w1, w2):
    return 3*w1**2 + 2*w1*w2


f(5, 3)

105

In [118]:
w1, w2 = 5, 3
eps = 5e-7
(f(w1+eps, w2) - f(w1, w2))/eps

36.000001500724466

In [119]:
(f(w1, w2 + eps) - f(w1, w2)) / eps

10.000000003174137

In [120]:
w1, w2 = tf.Variable(5.0), tf.Variable(3.0)

with tf.GradientTape() as tape:
    z = f(w1, w2)

In [121]:
tape.gradient(z, w1)  # dz/dw1

<tf.Tensor: shape=(), dtype=float32, numpy=36.0>

In [122]:
try:
    print(tape.gradient(z, w2))
except Exception as ex:
    print(ex)

A non-persistent GradientTape can only be used to compute one set of gradients (or jacobians)


that happen because the tape is deleted once it used, preventing accumulating the gradients.


In [123]:
with tf.GradientTape(persistent=True) as tape:
    z = f(w1, w2)
print(tape.gradient(z, w1))
print(tape.gradient(z, w2))
del tape

tf.Tensor(36.0, shape=(), dtype=float32)
tf.Tensor(10.0, shape=(), dtype=float32)


can compute gradient for all variables once:


In [124]:
w1, w2 = tf.Variable(5.), tf.Variable(3.)
with tf.GradientTape() as tape:
    z = f(w1, w2)

gradients = tape.gradient(z, [w1, w2])
gradients

[<tf.Tensor: shape=(), dtype=float32, numpy=36.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=10.0>]

can't compute gradients for constant directly:


In [125]:
c1, c2 = tf.constant(5.0), tf.constant(3.0)
with tf.GradientTape() as tape:
    z = f(c1, c2)

tape.gradient(z, [c1, c2])

[None, None]

fixed by forcing tf to watch them:


In [126]:
c1, c2 = tf.constant(5.0), tf.constant(3.0)
with tf.GradientTape() as tape:
    tape.watch([c1, c2])
    z = f(c1, c2)

tape.gradient(z, [c1, c2])

[<tf.Tensor: shape=(), dtype=float32, numpy=36.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=10.0>]

In [127]:
# extra code – if given a vector, tape.gradient() will compute the gradient of
#              the vector's sum.
with tf.GradientTape() as tape:
    z1 = f(w1, w2 + 2.)
    z2 = f(w1, w2 + 5.)
    z3 = f(w1, w2 + 7.)

tape.gradient([z1, z2, z3], [w1, w2])

[<tf.Tensor: shape=(), dtype=float32, numpy=136.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=30.0>]

In [128]:
# extra code – shows that we get the same result as the previous cell
with tf.GradientTape() as tape:
    z1 = f(w1, w2 + 2.)
    z2 = f(w1, w2 + 5.)
    z3 = f(w1, w2 + 7.)
    z = z1 + z2 + z3

tape.gradient(z, [w1, w2])

[<tf.Tensor: shape=(), dtype=float32, numpy=136.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=30.0>]

In [129]:
# extra code – shows how to compute the jacobians and the hessians

with tf.GradientTape(persistent=True) as hessian_tape:
    with tf.GradientTape() as jacobian_tape:
        z = f(w1, w2)
    jacobians = jacobian_tape.gradient(z, [w1, w2])
hessians = [hessian_tape.gradient(jacobian, [w1, w2])
            for jacobian in jacobians]
del hessian_tape

In [130]:
hessians

[[<tf.Tensor: shape=(), dtype=float32, numpy=6.0>,
  <tf.Tensor: shape=(), dtype=float32, numpy=2.0>],
 [<tf.Tensor: shape=(), dtype=float32, numpy=2.0>, None]]

#### Blocking gradients


In [131]:
def f(w1, w2):
    # this will act normally on forward pass, but block/neglect the second part in backpropagation
    return 3*w1**2 + tf.stop_gradient(2*w1*w2)


with tf.GradientTape() as tape:
    z = f(w1, w2)
tape.gradient(z, [w1, w2])

[<tf.Tensor: shape=(), dtype=float32, numpy=30.0>, None]

numerical issues when using sqrt at very small values:


In [132]:
x = tf.Variable(1e-50)
with tf.GradientTape() as tape:
    z = tf.sqrt(x)

tape.gradient(z, [x])

[<tf.Tensor: shape=(), dtype=float32, numpy=inf>]

it produces inf


In [133]:
x = tf.Variable(1e-50)
with tf.GradientTape() as tape:
    z = tf.sqrt(x)

tape.gradient(z, [x])

[<tf.Tensor: shape=(), dtype=float32, numpy=inf>]

converting to float64 increase the precision and solves the problem


In [134]:
x = tf.Variable(1e-50, dtype=tf.float64)
with tf.GradientTape() as tape:
    z = tf.sqrt(x)

tape.gradient(z, [x])

[<tf.Tensor: shape=(), dtype=float64, numpy=4.999999999999999e+24>]

In [135]:
tf.math.log(tf.exp(tf.constant(30., dtype=tf.float32))+1.)

<tf.Tensor: shape=(), dtype=float32, numpy=30.0>

In [136]:
def my_softplus(z):
    return tf.math.log(1.0 + tf.exp(z))

In [137]:
my_softplus(100.)

<tf.Tensor: shape=(), dtype=float32, numpy=inf>

it explodes due to exp


In [138]:
# rewrite it to be more stable
def my_softplus(z):
    return tf.math.log(1 + tf.exp(-tf.abs(z))) + tf.maximum(0., z)

In [139]:
my_softplus(100.0)

<tf.Tensor: shape=(), dtype=float32, numpy=100.0>

works fine..


rewrite the function with stable gradients:


In [140]:
@tf.custom_gradient
def my_softplus(z):
    def my_softplus_gradients(grads):
        return grads * (1 - 1/(1+tf.exp(z)))
    result = tf.math.log(1 + tf.exp(-tf.abs(z))) + tf.maximum(0., z)
    return result, my_softplus_gradients

In [141]:
# extra code – shows that the function is now stable, as well as its gradients
x = tf.Variable([1000.])
with tf.GradientTape() as tape:
    z = my_softplus(x)

z, tape.gradient(z, [x])

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1000.], dtype=float32)>,
 [<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>])

---


### Custom Training Loops:


In [142]:
tf.keras.utils.set_random_seed(42)  # extra code – to ensure reproducibility
l2_reg = tf.keras.regularizers.l2(0.05)
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(30, activation="relu", kernel_initializer="he_normal",
                          kernel_regularizer=l2_reg),
    tf.keras.layers.Dense(1, kernel_regularizer=l2_reg)
])


def random_batch(X, y, batch_size=32):
    idx = np.random.randint(len(X), size=batch_size)
    return X[idx], y[idx]


def print_status_bar(step, total, loss, metrics=None):
    metrics = " - ".join([f"{m.name}: {m.result():.4f}"
                          for m in [loss] + (metrics or [])])
    end = "" if step < total else "\n"
    print(f"\r{step}/{total} - " + metrics, end=end)

# \r moves the cursor to the start of the current line to make the visual changes like fit() method progress


tf.keras.utils.set_random_seed(42)

n_epochs = 5
batch_size = 32
n_steps = len(X_train) // batch_size
optimizer = tf.keras.optimizers.SGD(learning_rate=0.01)
loss_fn = tf.keras.losses.mse
mean_loss = tf.keras.metrics.Mean()
metrics = [tf.keras.metrics.MeanAbsoluteError()]

In [143]:
for epoch in range(1, n_epochs+1):
    print(f"Epoch {epoch}/{n_epochs}")
    for step in range(1+n_steps):
        X_batch, y_batch = random_batch(X_train_scaled, y_train)
        with tf.GradientTape() as tape:
            y_pred = model(X_batch, training=True)
            main_loss = tf.reduce_mean(loss_fn(y_batch, y_pred))
            loss = tf.add_n([main_loss] + model.losses)
        gradients = tape.gradient(loss, model.trainable_variables)
        optimizer.apply_gradients(zip(gradients, model.trainable_variables))

        # extra code – if your model has variable constraints
        for variable in model.variables:
            if variable.constraint is not None:
                variable.assign(variable.constraint(variable))

        mean_loss(loss)
        for metric in metrics:
            metric(y_batch, y_pred)

        print_status_bar(step, n_steps, mean_loss, metrics)

    for metric in [mean_loss] + metrics:
        try:
            metric.reset_states()
        except:
            metric.reset_state()

Epoch 1/5
362/362 - mean: 3.5380 - mean_absolute_error: 0.6633
Epoch 2/5
362/362 - mean: 1.8658 - mean_absolute_error: 0.5431
Epoch 3/5
362/362 - mean: 1.1396 - mean_absolute_error: 0.5027
Epoch 4/5
362/362 - mean: 0.8489 - mean_absolute_error: 0.4980
Epoch 5/5
362/362 - mean: 0.7253 - mean_absolute_error: 0.5007


extra code – shows how to use the tqdm package to display nice progress bars


In [144]:
from tqdm.notebook import trange
from collections import OrderedDict
with trange(1, n_epochs + 1, desc="All epochs") as epochs:
    for epoch in epochs:
        with trange(1, n_steps + 1, desc=f"Epoch {epoch}/{n_epochs}") as steps:
            for step in steps:
                X_batch, y_batch = random_batch(X_train_scaled, y_train)
                with tf.GradientTape() as tape:
                    y_pred = model(X_batch)
                    main_loss = tf.reduce_mean(loss_fn(y_batch, y_pred))
                    loss = tf.add_n([main_loss] + model.losses)

                gradients = tape.gradient(loss, model.trainable_variables)
                optimizer.apply_gradients(
                    zip(gradients, model.trainable_variables))

                for variable in model.variables:
                    if variable.constraint is not None:
                        variable.assign(variable.constraint(variable))

                status = OrderedDict()
                mean_loss(loss)
                status["loss"] = mean_loss.result().numpy()
                for metric in metrics:
                    metric(y_batch, y_pred)
                    status[metric.name] = metric.result().numpy()

                steps.set_postfix(status)

        for metric in [mean_loss] + metrics:
            try:
                metric.reset_states()
            except:
                metric.reset_state()

All epochs:   0%|          | 0/5 [00:00<?, ?it/s]

Epoch 1/5:   0%|          | 0/362 [00:00<?, ?it/s]

Epoch 2/5:   0%|          | 0/362 [00:00<?, ?it/s]

Epoch 3/5:   0%|          | 0/362 [00:00<?, ?it/s]

Epoch 4/5:   0%|          | 0/362 [00:00<?, ?it/s]

Epoch 5/5:   0%|          | 0/362 [00:00<?, ?it/s]

---


### TensorFlow Functions and Graphs


In [145]:
def cube(n):
    return n**3


cube(2)

8

In [146]:
cube(tf.Variable(2.0))

<tf.Tensor: shape=(), dtype=float32, numpy=8.0>

In [147]:
cube(tf.constant(2.0))

<tf.Tensor: shape=(), dtype=float32, numpy=8.0>

In [148]:
tf.function(cube)

In [149]:
tf_cube = tf.function(cube)
tf_cube

In [150]:
tf_cube(2.0)

<tf.Tensor: shape=(), dtype=float32, numpy=8.0>

In [151]:
tf_cube(tf.constant(2.0))

<tf.Tensor: shape=(), dtype=float32, numpy=8.0>

we can also use decorator:


In [152]:
@tf.function
def cube(n):
    return n**3


cube(2.0)

<tf.Tensor: shape=(), dtype=float32, numpy=8.0>

the original python function still available:


In [153]:
tf_cube.python_function

<function __main__.cube(n)>

In [154]:
tf_cube.python_function(2.0)

8.0

let's try XLA (accelerated linear algebra) optimization in code by putting jit_compile=True in compile function:


In [6]:
import tensorflow as tf

# Check if GPU is available
print("Num GPUs Available: ", len(
    tf.config.experimental.list_physical_devices('GPU')))

# List available devices
print("Available devices:", tf.config.experimental.list_physical_devices())


# nvidia-smi for real time gpu monitoring

Num GPUs Available:  1
Available devices: [PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
