In [1]:
import tensorflow as tf

### Tensors and Operations


In [15]:
t = tf.constant([[1, 2, 3], [4, 5, 6]])
t

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [16]:
t.shape

TensorShape([2, 3])

In [17]:
t.numpy()

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
print(t[0, 0])
print(t[:, 2])

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([3 6], shape=(2,), dtype=int32)


In [19]:
t[..., :]

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [20]:
t[..., 1, tf.newaxis]  # keep dimension 1

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[2],
       [5]])>

In [21]:
t+10

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[11, 12, 13],
       [14, 15, 16]])>

In [22]:
t.__add__(10)  # not in-place

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[11, 12, 13],
       [14, 15, 16]])>

In [23]:
t

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [24]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  4,  9],
       [16, 25, 36]])>

In [25]:
t @ tf.transpose(t)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 32],
       [32, 77]])>

### Tensors and NumPy


In [26]:
import numpy as np

In [27]:
a = np.array([2., 4., 5.])
tf.constant(a)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2., 4., 5.])>

In [28]:
tf.square(a)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 4., 16., 25.])>

In [29]:
np.square(t)

array([[ 1,  4,  9],
       [16, 25, 36]])

### Type Conversions


In [30]:
try:
    tf.constant(2.0) + tf.constant(40)
except tf.errors.InvalidArgumentError as ex:
    print(ex)

cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a int32 tensor [Op:AddV2] name: 


In [31]:
try:
    tf.constant(2.0) + tf.constant(40., dtype=tf.float64)
except tf.errors.InvalidArgumentError as ex:
    # defualt values in tensorflow are float32, cannot manipulated with float64
    print(ex)

cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a double tensor [Op:AddV2] name: 


In [32]:
tf.constant(2.) + tf.constant(50, dtype=tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=52.0>

In [33]:
t2 = tf.constant(40, dtype=tf.float64)
tf.constant(2.) + tf.cast(t2, tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=42.0>

### Variables


In [34]:
v = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [35]:
v.assign(2*v)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

In [36]:
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

In [37]:
v[0, 0].assign(42)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[42.,  4.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

In [38]:
v.scatter_nd_update(indices=[[0, 0], [1, 0]], updates=[100, 400])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[100.,   4.,   6.],
       [400.,  10.,  12.]], dtype=float32)>

In [39]:
try:
    t[1] = [7., 8., 9.]  # cannot update with direct assignment
except TypeError as ex:
    print(ex)

'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment


### Custom Loss Function


In [40]:
def huber_fn(y_true, y_pred):
    """combine MSE smoothing property (at small values) and MAE outliers robustness property (at large values)"""
    error = abs(y_true-y_pred)
    squared = tf.square(error) / 2  # smoothing gradients factor
    # -.5 for connection guaranteed between two losses at the threshold (1 here)
    linear = error - .5
    return tf.where(error < 1, squared, linear)

In [41]:
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

housing = fetch_california_housing()
X_train_full, X_test, y_train_full, y_test = train_test_split(
    housing.data, housing.target.reshape(-1, 1), random_state=42)
X_train, X_valid, y_train, y_valid = train_test_split(
    X_train_full, y_train_full, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_valid_scaled = scaler.transform(X_valid)
X_test_scaled = scaler.transform(X_test)

input_shape = X_train.shape[1:]

tf.keras.utils.set_random_seed(42)
model = tf.keras.Sequential([
    tf.keras.layers.Dense(30, activation="relu", kernel_initializer="he_normal",
                          input_shape=input_shape),
    tf.keras.layers.Dense(1),
])

C:\Users\sayed\AppData\Roaming\Python\Python310\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [42]:
model.compile(loss=huber_fn, metrics=['mae'], optimizer='nadam')

model.fit(X_train_scaled, y_train, epochs=2,
          validation_data=(X_valid_scaled, y_valid))

Epoch 1/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.7494 - mae: 1.1371 - val_loss: 0.3474 - val_mae: 0.6522
Epoch 2/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 805us/step - loss: 0.2607 - mae: 0.5681 - val_loss: 0.2553 - val_mae: 0.5383


### Saving/Loading Models with Custom objects


In [43]:
import os
os.makedirs('saved_models', exist_ok=True)

In [44]:
model.save('saved_models/my_model_with_custom_hyper_loss.keras')

Load the model:


In [45]:
model = tf.keras.models.load_model(
    'saved_models/my_model_with_custom_hyper_loss.keras', custom_objects={'huber_fn': huber_fn})

In [46]:
model.fit(X_train_scaled, y_train, epochs=2,
          validation_data=(X_valid_scaled, y_valid))

Epoch 1/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.2188 - mae: 0.5096 - val_loss: 0.2129 - val_mae: 0.4876
Epoch 2/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 801us/step - loss: 0.1990 - mae: 0.4809 - val_loss: 0.1891 - val_mae: 0.4610


#### Now, We need to control the threshold..


In [47]:
def create_huber(threshold=1.0):
    def huber_fn(y_true, y_pred):
        error = y_true - y_pred
        is_small_error = tf.abs(error) < threshold
        squared_loss = tf.square(error) / 2
        linear_loss = threshold * tf.abs(error) - threshold ** 2 / 2
        return tf.where(is_small_error, squared_loss, linear_loss)
    return huber_fn

In [48]:
model.compile(loss=create_huber(2.0), metrics=['mae'], optimizer='nadam')

In [49]:
model.fit(X_train_scaled, y_train, epochs=2,
          validation_data=(X_valid_scaled, y_valid))

Epoch 1/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.2148 - mae: 0.4689 - val_loss: 0.2084 - val_mae: 0.4504
Epoch 2/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - loss: 0.2054 - mae: 0.4597 - val_loss: 0.1807 - val_mae: 0.4340


In [50]:
model.save("saved_models/my_model_with_a_custom_loss_threshold_2.keras")

In [51]:
model = tf.keras.models.load_model("saved_models/my_model_with_a_custom_loss_threshold_2.keras",
                                   custom_objects={"huber_fn": create_huber(2.0)})

so the threshold will not be saved with the model, but we must pass it..


In [52]:
model.fit(X_train_scaled, y_train, epochs=2,
          validation_data=(X_valid_scaled, y_valid))

Epoch 1/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.2000 - mae: 0.4540 - val_loss: 0.1853 - val_mae: 0.4339
Epoch 2/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 809us/step - loss: 0.1959 - mae: 0.4490 - val_loss: 0.1976 - val_mae: 0.4367


now we need to build huber function that saves the threshold with it, we must use sub-classing..


In [53]:
import keras

### Sub-Classing Custom Loss Function with automatically saved hyperparameters


In [54]:
@keras.utils.register_keras_serializable()
class HuberLoss(tf.keras.losses.Loss):
    def __init__(self, threshold=1.0, **kwargs):
        self.threshold = threshold
        super().__init__(**kwargs)

    def call(self, y_true, y_pred):
        error = y_true - y_pred
        is_small_error = tf.abs(error) < self.threshold
        squared_loss = tf.square(error) / 2
        linear_loss = self.threshold * tf.abs(error) - self.threshold**2 / 2
        return tf.where(is_small_error, squared_loss, linear_loss)

    def get_config(self):
        base_config = super().get_config()
        return {**base_config, "threshold": self.threshold}

In [55]:
tf.keras.utils.set_random_seed(42)
model = tf.keras.Sequential([
    tf.keras.layers.Dense(30, activation="relu", kernel_initializer="he_normal",
                          input_shape=input_shape),
    tf.keras.layers.Dense(1),
])

model.compile(loss=HuberLoss(2.), optimizer="nadam", metrics=["mae"])

model.fit(X_train_scaled, y_train, epochs=2,
          validation_data=(X_valid_scaled, y_valid))

Epoch 1/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 1.0512 - mae: 1.1438 - val_loss: 0.5086 - val_mae: 0.6718
Epoch 2/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - loss: 0.3170 - mae: 0.5816 - val_loss: 0.3527 - val_mae: 0.5571


In [56]:
model.save("saved_models/my_model_with_a_custom_loss_class.keras")

> Note: when using sub-classing, either passing the custom class used as custom objects, or decorate the class with @keras.utils.register_keras_serializable(),


In [57]:
model = tf.keras.models.load_model('saved_models/my_model_with_a_custom_loss_class.keras'
                                   #    ,custom_objects={'HuberLoss': HuberLoss}
                                   )

In [58]:
model.loss

here's, it identify it even without passing it as custom object to load_model function


---


### Custom Activation Functions, Initializers, Regularizers,and Constraints


In [59]:
def my_softplus(z):
    return tf.math.log(1.0 + tf.exp(z))


def my_glorot_initializer(shape, dtype=tf.float32):
    stddev = tf.sqrt(2. / (shape[0] + shape[1]))
    return tf.random.normal(shape, stddev=stddev, dtype=dtype)


def my_l1_regularizer(weights):
    return tf.reduce_sum(tf.abs(0.01 * weights))


def my_positive_weights(weights):  # return value is just tf.nn.relu(weights)
    return tf.where(weights < 0., tf.zeros_like(weights), weights)

In [60]:
layer = tf.keras.layers.Dense(1, activation=my_softplus,
                              kernel_initializer=my_glorot_initializer,
                              kernel_regularizer=my_l1_regularizer,
                              kernel_constraint=my_positive_weights)

Full example using custom functions above


In [61]:
tf.keras.utils.set_random_seed(42)

try:
    model = tf.keras.Sequential([
        tf.keras.layers.Dense(30, activation="relu", kernel_initializer="he_normal",
                              input_shape=input_shape),
        tf.keras.layers.Dense(1, activation=my_softplus,
                              kernel_initializer=my_glorot_initializer,
                              kernel_regularizer=my_l1_regularizer,
                              kernel_constraint=my_positive_weights)
    ])
    model.compile(loss="mse", optimizer="nadam", metrics=["mae"])
    model.fit(X_train_scaled, y_train, epochs=2,
              validation_data=(X_valid_scaled, y_valid))
    model.save("saved_models/my_model_with_many_custom_parts")
    model = tf.keras.models.load_model(
        "saved_models/my_model_with_many_custom_parts",
        custom_objects={
            "my_l1_regularizer": my_l1_regularizer,
            "my_positive_weights": my_positive_weights,
            "my_glorot_initializer": my_glorot_initializer,
            "my_softplus": my_softplus,
        }
    )
    model.fit(X_train_scaled, y_train, epochs=2,
              validation_data=(X_valid_scaled, y_valid))

except Exception as ex:
    print(ex)

Invalid value for attribute `regularizer`. Expected an instance of `keras.regularizers.Regularizer`, or `None`. Received: regularizer=<function my_l1_regularizer at 0x0000018BEB877520>


here's a problem with directly assignment regular functions, we should do it with sub-classing


In [62]:
# Custom Regularizer
class MyL1Regularizer(tf.keras.regularizers.Regularizer):
    def __init__(self, factor=0.01):
        self.factor = factor

    def __call__(self, x):
        return tf.reduce_sum(tf.abs(self.factor * x))

    def get_config(self):
        return {"factor": self.factor}

# Custom Constraint


class MyPositiveWeights(tf.keras.constraints.Constraint):
    def __call__(self, weights):
        return tf.nn.relu(weights)

    def get_config(self):
        return {}

# Custom Initializer


class MyGlorotInitializer(tf.keras.initializers.Initializer):
    def __init__(self):
        super(MyGlorotInitializer, self).__init__()

    def __call__(self, shape, dtype=tf.float32):
        stddev = tf.sqrt(2. / (shape[0] + shape[1]))
        return tf.random.normal(shape, stddev=stddev, dtype=dtype)

    def get_config(self):
        return {}

# Custom Activation Function


def my_softplus(z):
    return tf.math.log(1.0 + tf.exp(z))

In [63]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(30, activation="relu", kernel_initializer="he_normal",
                          input_shape=input_shape),
    tf.keras.layers.Dense(1, activation=my_softplus,
                          kernel_initializer=MyGlorotInitializer(),
                          kernel_regularizer=MyL1Regularizer(),
                          kernel_constraint=MyPositiveWeights())
])

model.compile(loss="mse", optimizer="nadam", metrics=["mae"])

# Fit model
model.fit(X_train_scaled, y_train, epochs=2,
          validation_data=(X_valid_scaled, y_valid))

# Save model
model.save("saved_models/my_model_with_many_custom_parts.keras")

# Load model
model = tf.keras.models.load_model(
    "saved_models/my_model_with_many_custom_parts.keras",
    custom_objects={
        "MyL1Regularizer": MyL1Regularizer,
        "MyPositiveWeights": MyPositiveWeights,
        "MyGlorotInitializer": MyGlorotInitializer,
        "my_softplus": my_softplus,
    }
)

# Continue training
model.fit(X_train_scaled, y_train, epochs=2,
          validation_data=(X_valid_scaled, y_valid))

Epoch 1/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 2.2008 - mae: 0.9706 - val_loss: inf - val_mae: inf
Epoch 2/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 790us/step - loss: 1.1249 - mae: 0.6767 - val_loss: inf - val_mae: inf
Epoch 1/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.8456 - mae: 0.5999 - val_loss: 2.8737 - val_mae: 0.5737
Epoch 2/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - loss: 0.6909 - mae: 0.5547 - val_loss: 2.0950 - val_mae: 0.5363


### Custom Metrics


In [64]:
# extra code – once again, lets' create a basic Keras model
tf.keras.utils.set_random_seed(42)
model = tf.keras.Sequential([
    tf.keras.layers.Dense(30, activation="relu", kernel_initializer="he_normal",
                          input_shape=input_shape),
    tf.keras.layers.Dense(1),
])
model.compile(loss="mse", optimizer="nadam", metrics=[create_huber(2.0)])

model.fit(X_train_scaled, y_train, epochs=2)

Epoch 1/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 680us/step - huber_fn: 1.0788 - loss: 2.5942
Epoch 2/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 582us/step - huber_fn: 0.3403 - loss: 0.7644


#### Streaming metrics


In [65]:
precision = tf.keras.metrics.Precision()
precision([0, 1, 1, 1, 0, 1, 0, 1], [1, 1, 0, 1, 0, 1, 0, 1])

<tf.Tensor: shape=(), dtype=float32, numpy=0.8>

In [66]:
precision([0, 1, 0, 0, 1, 0, 1, 1], [1, 0, 1, 1, 0, 0, 0, 0])

<tf.Tensor: shape=(), dtype=float32, numpy=0.5>

In [67]:
precision.result()

<tf.Tensor: shape=(), dtype=float32, numpy=0.5>

In [68]:
precision.variables

[<KerasVariable shape=(1,), dtype=float32, path=precision/true_positives>,
 <KerasVariable shape=(1,), dtype=float32, path=precision/false_positives>]

clear stored accumulated variables


In [69]:
precision.reset_state()
precision.result()

<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

Creating a streaming metric:


In [70]:
tf.keras.backend.clear_session()

In [71]:

@keras.utils.register_keras_serializable()
class HuberMetric(tf.keras.metrics.Metric):
    def __init__(self, threshold=1.0, **kwargs):
        super().__init__(**kwargs)  # handles base args (e.g., dtype)
        self.threshold = threshold
        self.huber_fn = create_huber(threshold)
        self.total = self.add_weight(
            name='total', initializer='zeros', shape=(), dtype=tf.float32)
        self.count = self.add_weight(
            name='count', initializer='zeros', shape=(), dtype=tf.float32)

    def update_state(self, y_true, y_pred, sample_weight=None):
        sample_metrics = self.huber_fn(y_true, y_pred)
        self.total.assign_add(tf.reduce_sum(sample_metrics))
        self.count.assign_add(tf.cast(tf.size(y_true), tf.float32))

    def result(self):
        return self.total / self.count

    def get_config(self):
        base_config = super().get_config()
        return {**base_config, "threshold": self.threshold}

In [72]:
m = HuberMetric(2.)

# total = 2 * |10 - 2| - 2²/2 = 14
# count = 1
# result = 14 / 1 = 14
m(tf.constant([[2.]]), tf.constant([[10.]]))

<tf.Tensor: shape=(), dtype=float32, numpy=14.0>

In [73]:
# total = total + (|1 - 0|² / 2) + (2 * |9.25 - 5| - 2² / 2) = 14 + 7 = 21
# count = count + 2 = 3
# result = total / count = 21 / 3 = 7
m(tf.constant([[0.], [5.]]), tf.constant([[1.], [9.25]]))

<tf.Tensor: shape=(), dtype=float32, numpy=7.0>

In [74]:
m.result()

<tf.Tensor: shape=(), dtype=float32, numpy=7.0>

In [75]:
print("Total:", m.total.numpy())  # This should print 21.0
print("Count:", m.count.numpy())  # This should print 3.0"

Total: 21.0
Count: 3.0


In [76]:
m.variables

[<KerasVariable shape=(), dtype=float32, path=huber_metric/total>,
 <KerasVariable shape=(), dtype=float32, path=huber_metric/count>]

In [77]:
m.reset_state()
m.variables

[<KerasVariable shape=(), dtype=float32, path=huber_metric/total>,
 <KerasVariable shape=(), dtype=float32, path=huber_metric/count>]

In [78]:
tf.keras.utils.set_random_seed(42)
model = tf.keras.Sequential([
    tf.keras.layers.Dense(30, activation="relu", kernel_initializer="he_normal",
                          input_shape=input_shape),
    tf.keras.layers.Dense(1),
])

model.compile(loss=create_huber(2.0), optimizer="nadam",
              metrics=[HuberMetric(2.0)])

In [79]:
model.fit(X_train_scaled, y_train, epochs=2)

Epoch 1/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 607us/step - huber_metric_1: 1.0512 - loss: 1.0512
Epoch 2/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 580us/step - huber_metric_1: 0.3170 - loss: 0.3170


In [80]:
model.save("saved_models/my_model_with_a_custom_metric.keras")

In [81]:
model = tf.keras.models.load_model(
    "saved_models/my_model_with_a_custom_metric.keras",
    custom_objects={
        "huber_fn": create_huber(2.0),
        "HuberMetric": HuberMetric
    }
)

In [82]:
model.fit(X_train_scaled, y_train, epochs=2)

Epoch 1/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 545us/step - huber_metric_1: 0.2612 - loss: 0.2612
Epoch 2/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 600us/step - huber_metric_1: 0.2328 - loss: 0.2328


In [83]:
try:
    model.metrics[-1].threshold
except Exception as ex:
    print(ex)

'CompileMetrics' object has no attribute 'threshold'


In [84]:
for metric in model.metrics:
    if isinstance(metric, HuberMetric):
        print(f"Huber Metric threshold: {metric.threshold}")

it seems like keras has updated from HOML tutorial, i will investigate where to find our threshold..


In [85]:
type(model.metrics[1])

keras.src.trainers.compile_utils.CompileMetrics

In [86]:
dir(model.metrics[-1])

['__annotations__',
 '__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_api_export_path',
 '_api_export_symbol_id',
 '_build_metrics_set',
 '_check_super_called',
 '_dtype',
 '_flat_metrics',
 '_flat_weighted_metrics',
 '_flatten_y',
 '_metrics',
 '_obj_type',
 '_tracker',
 '_unpickle_model',
 '_user_metrics',
 '_user_weighted_metrics',
 '_variables',
 'add_variable',
 'add_weight',
 'build',
 'built',
 'dtype',
 'from_config',
 'get_config',
 'metrics',
 'name',
 'output_names',
 'reset_state',
 'result',
 'stateless_reset_state',
 'stateless_result',
 'stateless_update_state',
 'update_state',
 'variables']

In [87]:
type(model.metrics[-1].metrics[0])

__main__.HuberMetric

In [88]:
model.metrics[-1].metrics[0].threshold

2.0

here it is :))))


Looks like it works fine! More simply, we could have created the class like this:


In [89]:
class HuberMetric(tf.keras.metrics.Mean):
    def __init__(self, threshold=1.0, name='HuberMetric', dtype=None):
        self.threshold = threshold
        self.huber_fn = create_huber(threshold)
        super().__init__(name=name, dtype=dtype)

    def update_state(self, y_true, y_pred, sample_weight=None):
        metric = self.huber_fn(y_true, y_pred)
        super(HuberMetric, self).update_state(metric, sample_weight)

    def get_config(self):
        base_config = super().get_config()
        return {**base_config, "threshold": self.threshold}

In [90]:
tf.keras.utils.set_random_seed(42)
model = tf.keras.Sequential([
    tf.keras.layers.Dense(30, activation="relu", kernel_initializer="he_normal",
                          input_shape=input_shape),
    tf.keras.layers.Dense(1),
])

model.compile(loss=tf.keras.losses.Huber(2.0), optimizer="nadam",
              weighted_metrics=[HuberMetric(2.0)])

np.random.seed(42)
sample_weight = np.random.rand(len(y_train))
history = model.fit(X_train_scaled, y_train, epochs=2,
                    sample_weight=sample_weight)

Epoch 1/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 577us/step - HuberMetric: 1.0599 - loss: 0.5274
Epoch 2/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 645us/step - HuberMetric: 0.3215 - loss: 0.1598


In [91]:
(history.history["loss"][0],
 history.history["HuberMetric"][0] * sample_weight.mean())

(0.3256884217262268, 0.32568849524955656)

In [92]:
model.save("saved_models/my_model_with_a_custom_metric_v2.keras")

In [93]:
model = tf.keras.models.load_model("saved_models/my_model_with_a_custom_metric_v2.keras",
                                   custom_objects={"HuberMetric": HuberMetric})

In [94]:
model.fit(X_train_scaled, y_train, epochs=2)

Epoch 1/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 603us/step - HuberMetric: 0.2627 - loss: 0.2262
Epoch 2/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 601us/step - HuberMetric: 0.2298 - loss: 0.1999


In [95]:
model.metrics[-1].metrics[-1].threshold

2.0

### Custom Layers


In [96]:
explayer = tf.keras.layers.Lambda(lambda x: tf.exp(x))

In [97]:
explayer(tf.constant([-1., 0., 1.]))

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.36787945, 1.        , 2.7182817 ], dtype=float32)>

or with sub-classing api


In [98]:
class MyDense(tf.keras.layers.Layer):
    def __init__(self, units, activation=None, **kwargs):
        super().__init__(**kwargs)
        self.units = units
        self.activation = tf.keras.activations.get(activation)

    def build(self, batch_input_shape):
        self.kernel = self.add_weight(
            name="kernel", shape=[batch_input_shape[-1], self.units],
            initializer="he_normal")
        self.bias = self.add_weight(
            name="bias", shape=[self.units], initializer="zeros")

    def call(self, X):
        return self.activation(X @ self.kernel + self.bias)

    def get_config(self):
        base_config = super().get_config()
        return {**base_config, "units": self.units,
                "activation": tf.keras.activations.serialize(self.activation)}

In [99]:
tf.keras.utils.set_random_seed(42)
model = tf.keras.Sequential([
    MyDense(30, activation="relu", input_shape=input_shape),
    MyDense(1)
])
model.compile(loss="mse", optimizer="nadam")
model.fit(X_train_scaled, y_train, epochs=2,
          validation_data=(X_valid_scaled, y_valid))
model.evaluate(X_test_scaled, y_test)
model.save("saved_models/my_model_with_a_custom_layer.keras")

Epoch 1/2


C:\Users\sayed\AppData\Local\Temp\ipykernel_14288\3097604586.py:3: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 991us/step - loss: 5.7265 - val_loss: 6.9255
Epoch 2/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 788us/step - loss: 0.9550 - val_loss: 2.6011
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 496us/step - loss: 0.7227


In [101]:
model = tf.keras.models.load_model("saved_models/my_model_with_a_custom_layer.keras",
                                   custom_objects={"MyDense": MyDense})
model.fit(X_train_scaled, y_train, epochs=2,
          validation_data=(X_valid_scaled, y_valid))

Epoch 1/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 914us/step - loss: 0.7034 - val_loss: 0.8613
Epoch 2/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 753us/step - loss: 0.5803 - val_loss: 0.4588


In [102]:
class MyMultiLayer(tf.keras.layers.Layer):
    def call(self, X):
        X1, X2 = X
        return X1+X2, X1*X2, X1/X2

In [103]:
inputs1 = tf.keras.layers.Input(shape=[2])
inputs2 = tf.keras.layers.Input(shape=[2])
MyMultiLayer()((inputs1, inputs2))

(<KerasTensor shape=(None, 2), dtype=float32, sparse=False, name=keras_tensor_20>,
 <KerasTensor shape=(None, 2), dtype=float32, sparse=False, name=keras_tensor_21>,
 <KerasTensor shape=(None, 2), dtype=float32, sparse=False, name=keras_tensor_22>)

In [104]:
X1, X2 = np.array([[3., 6.], [2., 7.]]), np.array([[6., 12.], [4., 3.]])
MyMultiLayer()((X1, X2))

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[ 9., 18.],
        [ 6., 10.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[18., 72.],
        [ 8., 21.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[0.5      , 0.5      ],
        [0.5      , 2.3333333]], dtype=float32)>)

Now let's create a layer with a different behavior during training and testing:


In [107]:
class MyGaussianNoise(tf.keras.layers.Layer):
    def __init__(self, stddev, **kwargs):
        super().__init__(**kwargs)
        self.stddev = stddev

    def call(self, X, training=None):
        if training:
            noise = tf.random.normal(tf.shape(X), stddev=self.stddev)
            return X + noise
        return X

In [108]:
tf.keras.utils.set_random_seed(42)
model = tf.keras.Sequential([
    MyGaussianNoise(stddev=1.0, input_shape=input_shape),
    tf.keras.layers.Dense(30, activation="relu",
                          kernel_initializer="he_normal"),
    tf.keras.layers.Dense(1)
])
model.compile(loss="mse", optimizer="nadam")
model.fit(X_train_scaled, y_train, epochs=2,
          validation_data=(X_valid_scaled, y_valid))
model.evaluate(X_test_scaled, y_test)

Epoch 1/2


C:\Users\sayed\AppData\Local\Temp\ipykernel_14288\1546716026.py:3: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 944us/step - loss: 2.7619 - val_loss: 25.1369
Epoch 2/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 731us/step - loss: 1.3951 - val_loss: 14.9793
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 484us/step - loss: 1.1219


1.1244221925735474

### Custom Models


In [131]:
tf.keras.backend.clear_session()

In [145]:
@tf.keras.utils.register_keras_serializable()
class ResidualBlock(tf.keras.layers.Layer):
    def __init__(self, n_layers, n_units, **kwargs):
        super().__init__(**kwargs)
        self.n_layers = n_layers
        self.n_units = n_units
        self.hidden = [tf.keras.layers.Dense(
            n_units, activation='relu', kernel_initializer="he_normal")
            for _ in range(n_layers)]

    def call(self, inputs):
        Z = inputs
        for layer in self.hidden:
            Z = layer(Z)
        return Z + inputs

    def get_config(self):
        config = super().get_config()
        config.update({
            "n_layers": self.n_layers,
            "n_units": self.n_units,
        })
        return config

In [146]:

@tf.keras.utils.register_keras_serializable()
class ResidualRegressor(tf.keras.models.Model):
    def __init__(self, output_dim, **kwargs):
        super().__init__(**kwargs)
        self.output_dim = output_dim
        self.linear1 = tf.keras.layers.Dense(30)
        self.rBlock1 = ResidualBlock(2, 30)
        self.rBlock2 = ResidualBlock(2, 30)
        self.out = tf.keras.layers.Dense(output_dim)

    def call(self, inputs):
        Z = self.linear1(inputs)
        for _ in range(1+3):
            Z = self.rBlock1(Z)
        Z = self.rBlock2(Z)
        return self.out(Z)

    def get_config(self):
        config = super().get_config()
        config.update({
            "output_dim": self.output_dim,
        })
        return config

In [148]:
tf.keras.utils.set_random_seed(42)
model = ResidualRegressor(1)
model.compile(loss="mse", optimizer="nadam")
history = model.fit(X_train_scaled, y_train, epochs=2)
score = model.evaluate(X_test_scaled, y_test)
model.save("saved_models/my_custom_model.keras")

model = tf.keras.models.load_model("saved_models/my_custom_model.keras")
history = model.fit(X_train_scaled, y_train, epochs=2)
model.predict(X_test_scaled[:3])

Epoch 1/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 2s 761us/step - loss: 38.7647
Epoch 2/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 766us/step - loss: 0.9498
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 562us/step - loss: 0.5812
Epoch 1/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 814us/step - loss: 0.6747
Epoch 2/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 759us/step - loss: 0.5269
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step


array([[1.0190629],
       [1.8359567],
       [4.045906 ]], dtype=float32)

Losses and Metrics Based on Model Internals


In [171]:
tf.keras.backend.clear_session()

In [179]:
class ReconstructingRegressor(tf.keras.Model):
    def __init__(self, output_dim, **kwargs):
        super().__init__(**kwargs)
        self.hidden = [tf.keras.layers.Dense(30, activation="relu",
                                             kernel_initializer="he_normal")
                       for _ in range(5)]
        self.out = tf.keras.layers.Dense(output_dim)
        self.reconstruction_mean = tf.keras.metrics.Mean(
            name="reconstruction_error")

    def build(self, batch_input_shape):
        n_inputs = batch_input_shape[-1]
        self.reconstruct = tf.keras.layers.Dense(n_inputs)

    def call(self, inputs, training=None):
        Z = inputs
        for layer in self.hidden:
            Z = layer(Z)
        reconstruction = self.reconstruct(Z)
        recon_loss = tf.reduce_mean(tf.square(reconstruction - inputs))
        self.add_loss(0.05 * recon_loss)
        if training:
            result = self.reconstruction_mean(recon_loss)
            self.add_metric(result)
        return self.out(Z)

In [181]:
tf.keras.utils.set_random_seed(42)
try:
    model = ReconstructingRegressor(1)
    model.compile(loss="mse", optimizer="nadam")
    history = model.fit(X_train_scaled, y_train, epochs=5)
    y_pred = model.predict(X_test_scaled)
except:
    print('error due to changes in tf new version (add metric deleted)')

Epoch 1/5
error due to changes in tf new version (add metric deleted)


### Computing Gradients Using Autodiff
